package coloti.telescope;

//import astri.telescope.EAstriTels;
//import astri.telescope.ERunMode;
//import astri.telescope.TelescopeController;
//import astri.telescope.config.ConfigManager;
//import astri.telescope.gui.AzElPanel;
//import astri.telescope.gui.JDMaint;
//import astri.telescope.gui.McsInfoPanel;
//import astri.telescope.gui.McsTerminal;
//import astri.telescope.mount.info.McsAzencInfo;
//import astri.telescope.mount.info.McsInterlocksInfo;
//import astri.weather.EAstriWs;
//import astri.weather.EWsStatus;
//import astri.weather.WeatherStationController;

import java.util.Hashtable;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.formdev.flatlaf.FlatDarkLaf;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gino
 */
public class TelColotiGui extends javax.swing.JFrame {

    private static Logger logger = LoggerFactory.getLogger(TelColotiGui.class);
    /**
     * Creates new form TestFrame
     */
    //private static TelescopeController tc;
    private ExecutorService pool;

    //private ConfigManager cm;

    //private AzElPanel azElPanel;

    //private EAstriTels tel;

    //private EAstriWs wsN;

    /* 
    public TelColotiGui(final EAstriTels tel, final EAstriWs wsN, final ERunMode rm) {
        super();
        // Create and display the form 
        //cm = new ConfigManager(rm);
        
        try {
            tc = new TelescopeController(cm, tel);
            if (tc.isTelActive()) {
                final WeatherStationController ws = new WeatherStationController(cm, wsN, logger);
                if (ws.isConnected() && ws.getStatus()==EWsStatus.LOADED)
                    tc.setWeatherStationConnector(ws);
                pool = Executors.newFixedThreadPool(2);
                initComponents();
            } else {
                logger.warn("impossible to activate Commention to the telescope");
            }
        } catch (final Exception e) {
            logger.error("Impossible to start", e.getMessage());

        }
        
    }
    */


    public TelColotiGui() {
        super();
    }

    /*
    public TelColotiGui(final TelescopeController tc) {
        super();
        this.tc = tc;
        pool = Executors.newFixedThreadPool(2);
        initComponents();

    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor- fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        JMenuItem jMiClearTp;
        JMenuItem jMiSetTp;
        JMenuItem jMiClose;
        JMenuItem jMiAzPanel;
        JMenuItem jMiInterPanel;
        JMenuItem jMcsPlcReset;
        JMenuItem jMcsPlcShutdown;
        JMenuItem jMcsResetAlarms;
        JMenuItem jMcsMaintDlg;
        JMenuItem jMiAzEncPanel;
        JMenuItem jMiInit;
        setTitle("ASTRI Telescope AIV Interface v.0.2");
        jMenuBar1 = new javax.swing.JMenuBar();
        jMTelescope = new javax.swing.JMenu();
        jMConfig = new javax.swing.JMenu();
        jMInfo = new javax.swing.JMenu();
        jMcsPlc = new javax.swing.JMenu();
        jMUtilities = new javax.swing.JMenu();
        jMiTerminal = new javax.swing.JMenuItem();
        jMiClearTp = new javax.swing.JMenuItem();
        jMiSetTp = new javax.swing.JMenuItem();
        jMiClose = new javax.swing.JMenuItem();
        jMiAzPanel = new javax.swing.JMenuItem();
        jMiInterPanel = new javax.swing.JMenuItem();
        jMiAzEncPanel = new javax.swing.JMenuItem();
        jMcsPlcReset = new javax.swing.JMenuItem();
        jMcsPlcShutdown = new javax.swing.JMenuItem();
        jMcsResetAlarms = new javax.swing.JMenuItem();
        jMcsMaintDlg = new javax.swing.JMenuItem();
        jMiInit = new javax.swing.JMenuItem();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(final WindowEvent e) {
                shutdown();
            }
        });

        jMTelescope.setText("Telescope");
        jMenuBar1.add(jMTelescope);

        jMiClose.setText("Close");
        jMTelescope.add(jMiClose);

        /* 
        jMiClose.addActionListener(e -> {
            shutdown();
        });*/

        jMConfig.setText("Config");
        jMenuBar1.add(jMConfig);

        jMInfo.setText("Info");
        jMenuBar1.add(jMInfo);

        jMiAzEncPanel.setText("Open Az Encoder Panel");
        jMInfo.add(jMiAzEncPanel);

        /*
        jMiAzEncPanel.addActionListener(e -> {
            final McsAzencInfo mcsAzEnc = new McsAzencInfo(tc.getMountController().getConnector());
            final McsInfoPanel tg1 = new McsInfoPanel(mcsAzEnc.getName(), mcsAzEnc);
            tg1.build().showPanel();
        });
        */

        jMcsPlc.setText("McsPLC");
        jMenuBar1.add(jMcsPlc);

        /*
        jMcsMaintDlg.setText("Open Maint. Panel");
        jMcsPlc.add(jMcsMaintDlg);
        jMcsMaintDlg.addActionListener(e -> {
            openMaintPanel();
        });

        jMcsResetAlarms.setText("Reset Plc Alarms");
        jMcsPlc.add(jMcsResetAlarms);
        jMcsResetAlarms.addActionListener(e -> {
            resetPlcAlarms();
        });

        jMcsPlcReset.setText("Restart Plc");
        jMcsPlc.add(jMcsPlcReset);
        jMcsPlcReset.addActionListener(e -> {
            restartPlc();
        });

        jMcsPlcShutdown.setText("Shutdown Plc");
        jMcsPlc.add(jMcsPlcShutdown);
        jMcsPlcShutdown.addActionListener(e -> {
            shutdownPlc();
        });

        jMUtilities.setText("Utilities");

        jMiTerminal.setText("Open Terminal");
        jMUtilities.add(jMiTerminal);
        jMiTerminal.addActionListener(e -> {
            pool.execute(new McsTerminal(tc, logger));
        });

        jMiAzPanel.setText("Open AZ-EL Panel");
        jMUtilities.add(jMiAzPanel);
        jMiAzPanel.addActionListener(e -> {
            azElPanel = new AzElPanel(tc.getMountController());
            azElPanel.showpanel();
        });

        jMiInterPanel.setText("Open Interlocks Panel");
        jMUtilities.add(jMiInterPanel);
        jMiInterPanel.addActionListener(e -> {
            final McsInterlocksInfo mcsInter = new McsInterlocksInfo(tc.getMountController().getConnector());
            final McsInfoPanel tg1 = new McsInfoPanel(mcsInter.getName(), mcsInter);
            tg1.build().showPanel();
        });

        jMiClearTp.setText("Clear Mcs TPoint");
        jMUtilities.add(jMiClearTp);
        jMiClearTp.addActionListener(e -> {
            tc.getObsManager().clearPointingModel();
        });

        jMiSetTp.setText("Set Mcs TPoint");
        jMUtilities.add(jMiSetTp);
        jMiSetTp.addActionListener(e -> {
            tc.getObsManager().uploadPointingModel();
        });
        */

        jMenuBar1.add(jMUtilities);

        setJMenuBar(jMenuBar1);
        //System.out.println("Start-11");
        //mainMotionPanel = new astri.telescope.gui.motion.MainMotionPanel(tc);
        //System.out.println("Start-12");
        //mainMotionPanel = new astri.telescope.gui.motion.MainMotionPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        /* 
        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainMotionPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mainMotionPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
                                */

        pack();

    }// </editor-fold>//GEN-END:initComponents

    /* 
    private void openMaintPanel() {
        final JDMaint dialog = new JDMaint(this, false);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(final java.awt.event.WindowEvent e) {
                dialog.dispose();
            }
        });
        dialog.setMountController(tc.getMountController());
        dialog.setVisible(true);

    }*/

    /* 
    private void resetPlcAlarms() {
        tc.getMountController().resetPlcAlarms();
        
    }

    private void shutdownPlc() {
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            tc.getMountController().shutdownPlc();
            

        }
    }*/

    private void checkUser(final Hashtable<String, String> login) {
        // connect to ldap;
    }

    /* 
    private void restartPlc() {
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            tc.getMountController().restartPlc();
            
        }
    }*/

    public Hashtable<String, String> login() {

        final Hashtable<String, String> logininformation = new Hashtable<String, String>();

        final JPanel panel = new JPanel(new BorderLayout(5, 5));

        final JPanel label = new JPanel(new GridLayout(0, 1, 2, 2));
        label.add(new JLabel("User", SwingConstants.RIGHT));
        label.add(new JLabel("Password", SwingConstants.RIGHT));
        panel.add(label, BorderLayout.WEST);

        final JPanel controls = new JPanel(new GridLayout(0, 1, 2, 2));
        final JTextField username = new JTextField();
        controls.add(username);
        final JPasswordField password = new JPasswordField();
        controls.add(password);
        panel.add(controls, BorderLayout.CENTER);

        final int result = JOptionPane.showConfirmDialog(
                this, panel, "login", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            logininformation.put("user", username.getText());
            logininformation.put("pass", new String(password.getPassword()));
            return logininformation;
        } else {
            return new Hashtable<String, String>();
        }
    }

    protected void shutdown() {

        //mainMotionPanel.close();
        //stopTelescope();
        //pool.shutdownNow();
        setVisible(false);
        dispose();

        System.exit(0);
    }
    
    /* 
    protected void stopTelescope() {
        tc.stopPublishTelescopeData();
        if (tc.getWeatherStationController() != null)
            tc.stopWeatherMonitor();
        tc.shutdown();
    }
    */

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) throws Exception {

        Locale.setDefault(new Locale("en", "US"));

        try {
            // Set cross-platform Java L&F (also called "Metal")
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (final UnsupportedLookAndFeelException e) {
            // handle exception
        }

        /* Create and display the form */

        /*
         * ConfigManager cm = new ConfigManager(ERunMode.DEV);
         * TelescopeController tc = new TelescopeController(cm, EAstriTels.ASTRI1);
         * WeatherStationController ws = new WeatherStationController(cm, EAstriWs.WS1,
         * logger);
         * ws.printLastValues();
         * tc.setWeatherStationConnector(ws);
         */

        // if (tc.isTelActive()) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelColotiGui(EAstriTels.ASTRI1, EAstriWs.WS1, ERunMode.DEV).setVisible(true);
                //new TelColotiGui(tc).setVisible(true);
                new TelColotiGui().setVisible(true);
                // new TestFrame().setVisible(true);
            }
        });
        // }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    //private astri.telescope.gui.motion.MainMotionPanel mainMotionPanel;

    private javax.swing.JMenu jMConfig;
    private javax.swing.JMenu jMInfo;
    private javax.swing.JMenu jMTelescope;
    private javax.swing.JMenu jMUtilities;
    private javax.swing.JMenu jMcsPlc;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMiTerminal;

    // End of variables declaration//GEN-END:variables
}
